### ISSUE TITLE
data/sales_data.csv  file is missing

### ISSUE THREAD

**Issue by guquandaju012** [jeroenjanssens/python-polars-the-definitive-guide#1]
hi, the data/sales_data.csv  file is missing, would you please add the file to the repo?
thanks a lot

**Comment by jeroenjanssens** [comment]
Hi @guquandaju012, @AdoHaha, 

Because you helped us out, we'd like to include you in the Acknowledgments. If you're OK with this, could you please reply here or send an email to jeroen@jeroenjanssens.com with your full name?

Thanks,

Jeroen
