### ISSUE TITLE
Missing files in data directory

### ISSUE THREAD

**Issue by Bramtimm** [jeroenjanssens/python-polars-the-definitive-guide#2]
Just a heads up issue for missing data files in the data directory, great read so far! 🚀 

missing files in `data` directory: 

**ch2.**
- `data/citibike/..` files are missing (i.e. also `data/citibike/nyc-neighborhoods.geojson`)
- `Guardian Sans` font is not available by default on my machine

**ch14.**
- missing `data/marketing use case/marketing_campaigns.csv`
- missing `data/marketing use case/sales_data.csv`

**ch16.**
- missing `data/citibike/*.parquet` - there is also a inconsistency between notebook/book as in notebook it reads `trips = pl.read_parquet("data/biketrips/*.parquet")`

**Comment by jeroenjanssens** [comment]
Thanks @Bramtimm! The missing files have been added and the text and notebooks have been updated.
